### ISSUE TITLE
labels?

### ISSUE THREAD

**Issue by shawngraham** [geoss/som_visualization_r#1]
Hi,

This is very cool; thank you for developing it! I'm just playing, mostly, but I wondered if you had any thoughts on how one would go about labelling each hexagon with a row id from the original data?

**Comment by geoss** [comment]
Hi Shawn,

Been away from that doe for awhile.  I think each hexagon could (should) contain multiple rows.  Some may contain very few (or even none).  Visualizing the assignment might be difficult on the Map.  You could make histograms or a density map of rows per cell.  Not immediately sure how…

## -SS

Seth E. Spielman, Asst. Professor of Geography
University of Colorado
www.sethspielman.org | seth.spielman@colorado.edu

**Comment by shawngraham** [comment]
Cheers, thanks!
