### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by ciri** [geoss/som_visualization_r#2]
I pulled the latest version and tried running the Example code, but I end up with a strange, blank plot. The SOM is built correctly though ...

Plot output:

![rplot](https://cloud.githubusercontent.com/assets/138018/14368349/78ce025a-fd1d-11e5-834c-730ee852e151.png)

**Comment by geoss** [comment]
No.  Seems to be dead.  I spent 20mins trying to trouble shoot but got nowhere.  Change seems to be in the `som` function.  .

**Comment by geoss** [comment]
I get:
`aSom <- som(data=as.matrix(scale(na.omit(usa.bg.som[,1:7]))), grid=aGrid, rlen=1, alpha=c(0.05, 0.01), keep.data=TRUE)
Error in matrix(0, nd * ncodes, nmaps) : 
  invalid 'nrow' value (too large or NA)
In addition: Warning message:
In nd * ncodes : NAs produced by integer overflow`

**Comment by calvinwy** [comment]
I tried to modify your code before I saw your comments, I think the newer version of SOM returns a list of one element for both "data" and "codes".  You just need to change som_obj$data and som_obj$codes into som_obj$data[[1]] and som_obj$codes[[1]].  It will work perfectly.
