### ISSUE TITLE
Issue: Error in supersom(list(X), ...) : argument "X" is missing, with no default.

### ISSUE THREAD

**Issue by pcikausername** [geoss/som_visualization_r#8]
Hi,

I get a: Error in supersom(list(X), ...) : argument "X" is missing, with no default, when running:

data <- as.matrix(scale(na.omit(usa.bg.som[,1:7])))
aSom <- som(data=data, grid=aGrid, rlen=1, alpha=c(0.05, 0.01), keep.data=FALSE)

Do you (or anyone) know how to resolve the issue?

**Comment by geoss** [comment]
Is supersom something you've created?  Seems external to this project?  There is no "supersom" in this repository?

**Comment by pcikausername** [comment]
To my knowledge I have not crated supersom. I get the error after the line:

aSom <- som(data=data, grid=aGrid, rlen=1, alpha=c(0.05, 0.01), keep.data=FALSE)

I will update R, and post the result after that.

**Comment by pcikausername** [comment]
The error reproduces itself after I installed R 3.6.3:

aSom <- som(data=data, grid=aGrid, rlen=1, alpha=c(0.05, 0.01), keep.data=FALSE)
Error in supersom(list(X), ...) : 
  argument "X" is missing, with no default

Could it be something with the kohonen package...

**Comment by geoss** [comment]
Yeah, I think it is from something external to this, possibly the kohonen package.
